- name: clean data dirs
  file:
    path: "{{ node_exporter_dir_conf }}"
    state: absent

- name: Remove the user 'node_exporter_user'
  ansible.builtin.user:
    name: "{{ node_exporter_user }}"
    state: absent
    remove: yes

- name: clean binary executable
  file:
    path: "{{ node_exporter_bin }}"
    state: absent
